// Client/src/pages/scoreboard/Clock.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";

const time = ref("00:00:00");

function updateTime() {
  const now = new Date();
  const hours = String(now.getHours()).padStart(2, "0");
  const minutes = String(now.getMinutes()).padStart(2, "0");
  const seconds = String(now.getSeconds()).padStart(2, "0");
  time.value = `${hours}:${minutes}:${seconds}`;
}

let intervalId: number;

onMounted(() => {
  updateTime();
  intervalId = setInterval(updateTime, 1000);
});

onUnmounted(() => {
  clearInterval(intervalId);
});
</script>

<template>
  <div class="font-mono">{{ time }}</div>
</template>

// scoreboard/src/app/clock.tsx
"use client";
import React, { useEffect, useState } from "react";
export default function Clock() {
  const [hours, setHours] = useState("");
  const [minutes, setMinutes] = useState("");
  const [seconds, setSeconds] = useState("");

  useEffect(() => {
    setInterval(() => {
      const date = new Date();
      const h = date.getHours().toString().padStart(2, "0");
      const m = date.getMinutes().toString().padStart(2, "0");
      const s = date.getSeconds().toString().padStart(2, "0");
      setHours(h);
      setMinutes(m);
      setSeconds(s);
    }, 1000);
  });
  return (
    <p>
      {hours}:{minutes}:{seconds}
    </p>
  );
}
